ALTER TABLE document_type MODIFY id
GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);

ALTER TABLE guest_status MODIFY id
GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);

ALTER TABLE payment_type MODIFY id
GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);

ALTER TABLE reservation_status MODIFY id
GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);

ALTER TABLE room_type MODIFY id
GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);

ALTER TABLE season_pricing MODIFY id
GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);

ALTER TABLE guest MODIFY id
GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);

ALTER TABLE payment MODIFY id
GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);

ALTER TABLE reservation MODIFY id
GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);